### ISSUE TITLE
Issue while searching "vijay nagar"

### ISSUE THREAD

**Issue by jordan9827** [lhamycodes/flutter_mapbox_autocomplete#7]
Unhandled Exception: type 'Null' is not a subtype of type 'PlaceType'
E/flutter (23288): #0      new List.from (dart:core-patch/array_patch.dart:40:5)
E/flutter (23288): #1      new MapBoxPlace.fromJson (package:flutter_mapbox_autocomplete/src/Predections.dart:84:19)

**Comment by lhamycodes** [comment]
I see that it's been forked and worked on by @neerajrcodiant

fork link: https://github.com/neerajrcodiant/flutter_mapbox_autocomplete

Maybe when done, you can make a PR to this repo

**Comment by thiagoadriano** [comment]
Hi @lhamycodes 
I opened a PR with the solution to this error.
You can check it out to go ahead with a build of this fix.

**Comment by scripta55** [comment]
@thiagoadriano i would suggest you remove null and add [] as the forked solution as well, above the types you have updated, just to make sure this doesn't happen again if more types are added by mapbox
